# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df866fa18de4f237621a4ce3800cefc5"
name = "consolidated-strategy-app"
handle = "consolidated-strategy-app-9"
application_url = "https://sorted-media-cuisine-jokes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "najia-store-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sorted-media-cuisine-jokes.trycloudflare.com/auth/callback",
  "https://sorted-media-cuisine-jokes.trycloudflare.com/auth/shopify/callback",
  "https://sorted-media-cuisine-jokes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
